include: [.well-known]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
permalink: pretty

title: fooyin
email: luket@pm.me
description: A customisable music player
url: "https://www.fooyin.org"
